apiVersion: apps/v1
kind: Deployment
metadata:
  name: hm-app
  namespace: home-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hm-app
  template:
    metadata:
      labels:
        app: hm-app
    spec:
      containers:
        - name: sonarr
          image: ghcr.io/linuxserver/sonarr
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Yerevan"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: sonarr
              containerPort: 8989
          volumeMounts:
            - name: hm-volume
              mountPath: /downloads
              subPath: ./home-media/downloads
            - name: hm-volume
              mountPath: /config
              subPath: ./home-media/sonarr/config
          resources:
            requests:
              memory: 256Mi
              cpu: 128m
            limits:
              memory: 512Mi
              cpu: 500m
      volumes:
        - name: hm-volume
          persistentVolumeClaim:
            claimName: hm-claim
