apiVersion: apps/v1
kind: Deployment
metadata:
  name: hm-app
  namespace: home-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hm-app
  template:
    metadata:
      labels:
        app: hm-app
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Yerevan"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: sonarr
              containerPort: 8989
          volumeMounts:
            - name: hm-volume
              mountPath: ./downloads
              subPath: ./home-media/downloads
            - name: cephfs-volume
              mountPath: /config
              subPath: ./home-media/sonarr/config
          resources:
            requests:
              memory: 500Mi
              cpu: 256m
            limits:
              memory: 1024Mi
              cpu: 500m
        - name: radarr
          image: linuxserver/radarr
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Yerevan"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: radarr-web
              containerPort: 7878
          volumeMounts:
            - name: hm-volume
              mountPath: /downloads
              subPath: ./home-media/downloads
            - name: cephfs-volume
              mountPath: /config
              subPath: ./home-media/radarr/config
          resources:
            requests:
              memory: 500Mi
              cpu: 256m
            limits:
              memory: 1024Mi
              cpu: 500m
        - name: transmission
          image: linuxserver/transmission
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: "Asia/Yerevan"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          ports:
            - name: torrent-web
              containerPort: 9091
              protocol: TCP
            - name: torrent-tcp
              containerPort: 31502
              protocol: TCP
            - name: torrent-udp
              containerPort: 31503
              protocol: UDP
          volumeMounts:
            - name: hm-volume
              mountPath: ./downloads
              subPath: ./home-media/downloads
            - name: cephfs-volume
              mountPath: ./config
              subPath: ./home-media/transmission/config
            - name: cephfs-volume
              mountPath: ./watch
              subPath: ./home-media/transmission/watch
          resources:
            requests:
              memory: 500Mi
              cpu: 128m
            limits:
              memory: 1024Mi
              cpu: 256m
        - name: jackett
          image: linuxserver/jackett
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: "Asia/Yerevan"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          ports:
            - name: jackett-web
              containerPort: 9117
              protocol: TCP
          volumeMounts:
            - name: hm-volume
              mountPath: ./downloads
              subPath: ./home-media/downloads
            - name: cephfs-volume
              mountPath: ./config
              subPath: ./home-media/jackett/config
          resources:
            requests:
              memory: 500Mi
              cpu: 128m
            limits:
              memory: 1024Mi
              cpu: 256m
        - name: jellyfin
          image: linuxserver/jellyfin
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: "Asia/Yerevan"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          ports:
            - name: jellyfin-web
              containerPort: 8096
            - name: jellyfin-tcp
              containerPort: 8920
            - name: jellyfin-udp
              containerPort: 7359
              protocol: UDP
          volumeMounts:
            - name: hm-volume
              mountPath: ./data
              subPath: ./home-media/downloads
            - name: cephfs-volume
              mountPath: ./config
              subPath: ./home-media/jellyfin/config
          resources:
            requests:
              memory: 500Mi
              cpu: 256m
            limits:
              memory: 1024Mi
              cpu: 500m
        - name: heimdall
          image: linuxserver/heimdall
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: "Asia/Yerevan"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          ports:
            - name: heimdall-web
              containerPort: 80
          volumeMounts:
            - name: cephfs-volume
              mountPath: ./config
              subPath: ./home-media/heimdall/config
          resources:
            requests:
              memory: 500Mi
              cpu: 256m
            limits:
              memory: 1024Mi
              cpu: 500m
      volumes:
        - name: hm-volume
          persistentVolumeClaim:
            claimName: hm-claim
        - name: cephfs-volume
          cephfs:
            monitors:
              - 192.168.50.10
            user: admin
            secretRef:
              name: ceph-secret
            readOnly: false
