apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hm-claim
  namespace: home-media
spec:
  volumeName: hm-nfs
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

--- 

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: hm-nfs
  namespace: home-media
spec: 
  accessModes: 
    - ReadWriteMany
  capacity: 
    storage: 100Gi
  nfs: 
    path: "/mnt/nfs_share"
    server: 192.168.5.3
  storageClassName: nfs
