apiVersion: v1
kind: Service
metadata:
  name: hm-svc
  namespace: home-media
spec:
  type: NodePort
  selector:
    app: hm-app
  ports:
  - name: sonarr-web
    port: 8989
    targetPort: 8989
    nodePort: 31500
  - name: radarr-web
    port: 7878
    targetPort: 7878
    nodePort: 30501
    protocol: TCP
  - name: torrent-web
    port: 9091
    targetPort: 9091
    nodePort: 31502
  - name: jackett-web
    port: 9117
    targetPort: 9117
    nodePort: 31503
  - name: jellyfin-web
    port: 8096
    targetPort: 8096
    nodePort: 31504
