apiVersion: v1
kind: Namespace
metadata:
  name: mynginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx_app
  namespace: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx_app
  template:
    metadata:
      labels:
        app: mynginx_app
    spec:
      containers:
      - name: mynginx_app
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: httpport
          containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mynginx-service
  namespace: mynginx
spec:
  type: LoadBalancer
  selector:
    app: mynginx_app
  ports:
  - name: httpport
    port: 80
    targetPort: 80
    nodePort: 32000

