apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-app
  namespace: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx-app
  template:
    metadata:
      labels:
        app: mynginx-app
    spec:
      containers:
      - name: mynginx-app
        image: d1nar1us/mynginx:v2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: httpport
          containerPort: 80
      imagePullSecrets:
      - name: mydockerhub
      #   volumeMounts:
      #   - name: myhtml
      #     mountPath: /usr/share/nginx/html/
      # volumes:
      # - name: myhtml
      #   configMap:
      #     name: index-html-configmap