apiVersion: v1
kind: Service
metadata:
  name: mynginx-service
  namespace: my-nginx
spec:
  type: NodePort 
  selector:
    app: mynginx-app
  ports:
  - name: httpport
    port: 80
    targetPort: 80
    nodePort: 32000