apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: my-jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-app
  ports:
  - name: httpport
    port: 8080
    targetPort: 8080
    nodePort: 30001
  - name: jnlpport
    targetPort: 50000
    port: 50000
    nodePort: 30002
  - name: dockerpport
    targetPort: 2375
    port: 2375
    nodePort: 30003
