name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - name: get tag version
        run: |
          TAG=cat VERSION
          echo $TAG
          pip install yq
          yq -r ./nginx/nginx.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mynginx:v2.0.1
