name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - name: get tag version
        run: |
          TAG=$(cat VERSION)
          echo $tag
          pip install yq
          yq --arg version "${tag}" '.spec.template.spec.containers[].image|= sub(split("nginx:")[1]; $version)' nginx/nginx.yaml -yi
          git config --global user.email "my_githubuser@example.com"
          git config --global user.name "My Github actions user"
          git add nginx/nginx.yaml
          git commit -m "updated by github actions"
          git push
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/mynginx:v2.0.1
