name: Publish Nginx Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - dockerfiles/nginx/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use python
        uses: actions/setup-python@v4
      - name: get tag version
        run: |
          tag=$(cat dockerfiles/nginx/VERSION)
          echo $tag
          pip install yq
          echo ######################################################
          cat nginx/nginx.yaml
          echo ######################################################
          yq --arg version "${tag}" '.spec.template.spec.containers[0].image|= sub(split("d1nar1us/mynginx:")[1]; $version)' nginx/nginx-app.yaml -yi
          cat nginx/nginx-app.yaml
      - name: git push
        run: |    
          git config --global user.email ${{ secrets.MYGITHUB_EMAIL }}
          git config --global user.name ${{ secrets.MYGITHUB_USERNAME }}
          git add nginx/nginx-app.yaml
          git commit -m "updated by github actions"
          git push
          echo $tag
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          tag=$(cat dockerfiles/nginx/VERSION)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mynginx:$tag dockerfiles/nginx/.
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mynginx:$tag
