name: new-test_wf

on:
  workflow_dispatch:
  workflow_run: 
    workflows: ["Publish Nginx Docker image"]
    types:
      - completed
  push:
    branches: [ "main" ]
    paths:
      - nginx/nginx.yaml

jobs:
  docker:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: use python
        uses: actions/setup-python@v4
      - name: test python
        run: python3 test.py
