name: new-test_wf

on:
  workflow_dispatch:
  workflow_run: 
    workflows: ["Publish Nginx Docker image"]
    types:
      - completed
  push:
    branches: [ "main" ]
    paths:
      - nginx/nginx-app.yaml

jobs:
  docker:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        run: echo "${{ vars.TEST_VERSION }}"
